Fix conda parsing error because of version specifier
The version specifier `~=2.7,>=2.7.2` become invalid in mamba and
results in the error

```
libmambapy.bindings.specs.ParseError: Error parsing version "'>=2.7.2". Version
contains invalid characters in '>=2.7.2.
```

This is fixed by using the equivalent specifier `<3.0.0,>=2.7.2`