Improve the error message when db tests cannot be run due to import error
When attempting to load db tests through the loadTestsFromName of the
test loader that contained import errors, an AttributeError would be
thrown with the cryptic message

	AttributeError: 'module' object has no attribute 'process'

To provide a more clear description of the problem we put the call to
load the tests in a try except block and catch the AttributeError.
If it is caught we attempt to import it, which should then trigger the
actual import error, which we then print to screen and exit