replace anaconda => defaults
it seems the anaconda channel is currently breaking installs

https://github.com/conda/conda/issues/7872

Here is the error I got:
```
     File "/home/travis/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment
```