verdi import --in-place between file systems
verdi import --in-place assumed that the temporary directory for the
migrated archive and the working directory are on the same file system.
If that was not the case, it would crash with

  OSError: [Errno 18] Invalid cross-device link

Switching from os.rename to shutil.move should resolve this issue.