fix: limit sqlalchemy<1.4.45
sqla 1.4.45 introduced a breaking change resulting in two test failures

FAILED tests/orm/test_querybuilder.py::TestRepresentations::test_as_sql_literal_quote - sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "['Si']" with datatype JSONB
FAILED tests/orm/test_querybuilder.py::test_analyze_query - sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "['x', 1]" with datatype JSONB