CLI: Usability improvements for interactive `verdi setup`
There were a number of ways that a user could break the command by
providing incorrect input that was not caught by validation:

 * The following options are now required and can no longer incorrectly
   be skipped with `!`: `user_email`, `user_first_name`, `user_last_name`
   `user_institution`, `db_engine`, `db_backend`, `db_host`, `db_port`
   and the `repository_path`.
 * For a missing parameter in interactive mode the error now reads:
      Error: Institution has to be specified
   Instead of:
      Error: Missing parameter: institution
   which should be more intuitive
 * The message that a profile has successfully been created is now only
   displayed if the storage backend initialized successfully. Before,
   this was shown before storage initialization, which could then still
   fail, making the success message confusing.