try to fix aiida.settings problem
aiida.settings was not documented because it failed writing the
config file

WARNING: autodoc: failed to import module u'aiida.settings'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/rtd_fix/local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/checkouts/rtd_fix/docs/source/../../aiida/settings.py", line 22, in <module>
    confs = get_config()
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/checkouts/rtd_fix/docs/source/../../aiida/common/setup.py", line 96, in get_config
    return check_and_migrate_config(_load_config())
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/checkouts/rtd_fix/docs/source/../../aiida/common/additions/config_migrations/_utils.py", line 39, in check_and_migrate_config
    store_config(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/checkouts/rtd_fix/docs/source/../../aiida/common/setup.py", line 141, in store_config
    with open(conf_file, "w") as json_file:
IOError: [Errno 2] No such file or directory: '/home/docs/.aiida/config.json'