Tests: add --db-backend pytest option (#6625)
Instead of choosing the database backend (SQLite or Postgres) implicitly via markers, we add an explicit `--db-backend ` option to pytest.

```
  --db-backend=DB_BACKEND
                        Database backend to be used for tests ('sqlite', 'psql')
```

- The default backend was changed from `psql` to `sqlite` to make local testing easier. 
- The tests running in CI are still using Postgres in most places.
- The only change in CI should be switching the rabbitmq tests and release tests to use sqlite.

Error if the user provides an invalid option

```
❯ pytest --db-backend=invalid
ERROR: Invalid --db-backend option 'invalid'
Must be one of: ('sqlite', 'psql')
```

To clarify, the existing presto marker works as before.